name: test_frontend

on:
  push:
    branches:
    tags:
    paths:
      - '.github/workflows/ci-test-frontend.yml'
      - 'frontend/**'
  pull_request:
    paths:
      - '.github/workflows/ci-test-frontend.yml'
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - run: npm ci --loglevel warn
        working-directory: ./frontend

      - run: npx run-p check lint
        working-directory: ./frontend

      - run: npm run check test
        working-directory: ./frontend
